steps:
  - name: bash
    entrypoint: bash
    args:
      - -c
      - |
        # Cloud SQL Proxy をバックグラウンドで起動
        /cloud-sql-proxy \
          --address=0.0.0.0 \
          --port=5432 \
          noten2-dev:asia-northeast2:test &

        # プロキシが準備完了するまで待機
        sleep 5

        # Flyway マイグレーションを実行
        flyway \
          -url=jdbc:postgresql://127.0.0.1:5432/postgres \
          -user=postgres \
          -password=xxx \
          -locations=filesystem:/workspace/backend/src/main/resources/db/migration-test \
          migrate
options:
  logging: 'CLOUD_LOGGING_ONLY'
