steps:
  # 1. Cloud SQL Proxy を起動
  - name: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
    entrypoint: /cloud-sql-proxy
    args:
      [
        "--address=0.0.0.0",
        "--port=5432",
        "noten2-dev:asia-northeast2:test"
      ]
    id: "proxy"
    waitFor: ['-']

  # 2. ポートチェック（Cloud SQL Proxy の準備完了を確認）
  - name: bash
    entrypoint: bash
    args:
      - -c
      - |
        echo "Testing network connectivity..."
        echo "Attempting to ping 'proxy'..."
        if ping -c 3 proxy; then
          echo "Ping to 'proxy' successful!"
        else
          echo "Ping to 'proxy' failed."
        fi
        echo "Checking if port 5432 on 'proxy' is accessible..."
        if nc -z proxy 5432; then
          echo "Port 5432 on 'proxy' is accessible."
        else
          echo "Port 5432 on 'proxy' is not accessible."
        fi
        echo "Retrieving local IP address..."
        ip addr show
    waitFor: ['-']
    id: "port-check"

  # 3. Flyway マイグレーションを実行
  - name: flyway/flyway:10
    entrypoint: flyway
    args:
      [
        "-url=jdbc:postgresql://127.0.0.1:5432/postgres",
        "-user=postgres",
        "-password=$_POSTGRES_PASSWORD",
        "-locations=filesystem:/workspace/backend/src/main/resources/db/migration-test",
        "migrate"
      ]
    waitFor: ["port-check"]

options:
  logging: 'CLOUD_LOGGING_ONLY'
