steps:
  # Cloud SQL Proxy を起動
  - name: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
    entrypoint: /cloud-sql-proxy
    args:
      [
        "--address=0.0.0.0",
        "--port=5432",
        "noten2-dev:asia-northeast2:test"
      ]

  # Flyway マイグレーションを実行
  - name: flyway/flyway:10
    entrypoint: flyway
    args:
      [
        "-url=jdbc:postgresql://127.0.0.1:5432/postgres",
        "-user=postgres",
        "-password=$_POSTGRES_PASSWORD",
        "-locations=filesystem:/workspace/backend/src/main/resources/db/migration-test",
        "migrate"
      ]
