steps:
  # 1. Docker ネットワーク情報を確認
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/sh
    args:
      - -c
      - |
        echo "Inspecting the cloudbuild network..."
        docker network inspect
        docker network inspect cloudbuild > /workspace/network-inspect.json
        echo "Network inspect information saved to /workspace/network-inspect.json"
        cat /workspace/network-inspect.json
        sleep 30
        echo "sleep end"
    waitFor: ['-']

  # 検証ステップ: `step_0` がホスト名として解決できるか確認
  - name: curlimages/curl:latest
    entrypoint: sh
    args:
      - -c
      - |
        echo "Testing hostname resolution..."
        if ping -c 3 step_0; then
          echo "step_0 hostname resolved successfully."
        else
          echo "step_0 hostname resolution failed."
        fi
    waitFor: ['-']

options:
  logging: 'CLOUD_LOGGING_ONLY'
