steps:
  # 1. Docker ネットワーク情報を確認
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/sh
    args:
      - -c
      - |
        echo "Inspecting the cloudbuild network..."
        docker network inspect cloudbuild > /workspace/network-inspect.json
        echo "Network inspect information saved to /workspace/network-inspect.json"
        cat /workspace/network-inspect.json

  # 2. Cloud SQL Proxy を起動
  - name: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
    entrypoint: /cloud-sql-proxy
    args:
      [
        "--address=0.0.0.0",
        "--port=5432",
        "noten2-dev:asia-northeast2:test"
      ]
    id: "proxy"

  # 3. Flyway マイグレーション
  - name: flyway/flyway:10
    entrypoint: flyway
    args:
      [
        "-url=jdbc:postgresql://proxy:5432/postgres",
        "-user=postgres",
        "-password=$_POSTGRES_PASSWORD",
        "-locations=filesystem:/workspace/backend/src/main/resources/db/migration-test",
        "migrate"
      ]
    waitFor: ["proxy"]

options:
  logging: 'CLOUD_LOGGING_ONLY'
