steps:
  # 0. ソケット用ディレクトリを作成
  - name: bash
    entrypoint: bash
    args:
      - -c
      - |
        mkdir -p /workspace/.cloudsql
        chmod 777 /workspace/.cloudsql
    id: "create-socket-dir"
    volumes:
      - name: cloudsql
        path: /workspace/.cloudsql
    waitFor: ["-"]

  # 1. Cloud SQL Proxy を起動
  - name: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
    entrypoint: /cloud-sql-proxy
    args:
      [
        "--unix-socket=/workspace/.cluodsql",
        "noten2-dev:asia-northeast2:test"
      ]
    id: "proxy"
    volumes:
      - name: cloudsql
        path: /workspace/.cloudsql
    waitFor: ["create-socket-dir"]

  # 2. Cloud SQL Proxy の起動待機
  - name: flyway/flyway:10
    entrypoint: bash
    args:
      - -c
      - |
        while [ ! -e "/workspace/.cloudsql" ]; do
          sleep 1
        done
    timeout: 60s
    id: "proxy-wait"
    waitFor: ["proxy"]

  # 3. Flyway マイグレーション
  - name: flyway/flyway:10
    entrypoint: flyway
    args:
      [
        "-url=jdbc:postgresql://127.0.0.1:5432/postgres",  # TCP接続の場合
        "-user=postgres",
        "-password=$_POSTGRES_PASSWORD",
        "-locations=filesystem:/workspace/backend/src/main/resources/db/migration-test",
        "migrate"
      ]
    waitFor: ["proxy-wait"]

options:
  logging: 'CLOUD_LOGGING_ONLY'
