server.port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/noten
    username: username
    password: password
  jpa:
    hibernate:
      # DDLを作り直したい場合はDBをdrop・createしてからcreate-onlyを指定
      ddl-auto: none
      show-sql: true
    properties.hibernate:
      show_sql: false
      format_sql: true
      use_sql_comments: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false
  output.ansi.enabled: always

noten:
  security:
    secret: noten
    expiration-time-msec: 7200000

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.springframework.orm.jpa.JpaTransactionManager: DEBUG
  org.springframework.transaction: DEBUG
  org.hibernate.transaction: DEBUG
