spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/noten
    username: username
    password: password
  jpa:
    hibernate:
      # DDLを作り直したい場合はDBをdrop・createしてからcreate-onlyを指定
      ddl-auto: none
      show-sql: true
    properties.hibernate:
      show_sql: false
      format_sql: true
      use_sql_comments: true
      dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration-mysql
