spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:noten.db
    username: sa
    password: sa
  jpa:
    hibernate:
      # DDLを作り直したい場合はDBをdrop・createしてからcreate-onlyを指定
      ddl-auto: none
      show-sql: true
    properties.hibernate:
      show_sql: false
      format_sql: true
      use_sql_comments: true
      dialect: org.hibernate.community.dialect.SQLiteDialect
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    locations: classpath:db/migration-sqlite
    # allow mixing transactional and non-transactional statements within the same migration
    mixed: true
