server.port: 8080

spring:
  application.name: backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/noten
    username: username
    password: password